// All static data for the website

export const SERVICES = [
  {
    id: 1,
    title: 'Building Construction',
    description: 'Complete building construction from foundation to finishing with superior quality materials and workmanship.',
    icon: 'Building2',
    color: '#1A6B7C',
  },
  {
    id: 2,
    title: 'House Construction',
    description: 'Custom house construction tailored to your dream design, budget, and timeline with full transparency.',
    icon: 'Home',
    color: '#1A6B7C',
  },
  {
    id: 3,
    title: 'Commercial Construction',
    description: 'Office buildings, showrooms, and commercial spaces built to meet industry standards and business needs.',
    icon: 'Landmark',
    color: '#1A6B7C',
  },
  {
    id: 4,
    title: 'Interior Design',
    description: 'Modern and elegant interior design solutions - from concept to completion for homes and offices.',
    icon: 'Sofa',
    color: '#D4813A',
  },
  {
    id: 5,
    title: 'Renovation',
    description: 'Transform your old spaces with expert renovation services that breathe new life into any structure.',
    icon: 'Wrench',
    color: '#D4813A',
  },
  {
    id: 6,
    title: 'Waterproofing',
    description: 'Advanced waterproofing solutions for rooftops, basements, and terraces to protect your property.',
    icon: 'Droplets',
    color: '#1A6B7C',
  },
  {
    id: 7,
    title: 'Painting',
    description: 'Professional interior and exterior painting services with premium paints and flawless finishing.',
    icon: 'Palette',
    color: '#D4813A',
  },
  {
    id: 8,
    title: 'Civil Engineering',
    description: 'Expert civil engineering consultancy, structural design, and soil testing for secure foundations.',
    icon: 'HardHat',
    color: '#1A6B7C',
  },
  {
    id: 9,
    title: 'Road Construction',
    description: 'Durable road construction and asphalting services for residential communities and public areas.',
    icon: 'Road',
    color: '#D4813A',
  },
  {
    id: 10,
    title: 'Roof Repair',
    description: 'Reliable roof repair, reinforcement, and replacement services to protect your property from damage.',
    icon: 'Triangle',
    color: '#1A6B7C',
  },
  {
    id: 11,
    title: 'Tile Work',
    description: 'Premium tile installation for floors, walls, kitchens, and bathrooms with precision and style.',
    icon: 'Grid3X3',
    color: '#D4813A',
  },
  {
    id: 12,
    title: 'Foundation Work',
    description: 'Strong and reliable foundation solutions built on thorough soil analysis and engineering expertise.',
    icon: 'Layers',
    color: '#1A6B7C',
  },
];

export const PROJECT_CATEGORIES = ['All', 'Residential', 'Commercial', 'Interior', 'Renovation'];

export const PROJECTS = [
  {
    id: 1,
    title: 'Modern Contemporary Residence',
    category: 'Residential',
    location: 'Gandhi Nagar, Udumalpet',
    year: '2024',
    image: '/images/projects/residential-contemporary-villa.webp',
    description: 'Custom contemporary single-floor residence with textured elevation and warm ambient lighting',
  },
  {
    id: 2,
    title: 'RMR Supermart Commercial Building',
    category: 'Commercial',
    location: 'Udumalpet',
    year: '2024',
    image: '/images/projects/commercial-rmr-supermart.webp',
    description: 'Turnkey commercial retail space construction with glass storefront, canopy, and wide frontage',
  },
  {
    id: 3,
    title: 'Natural Slate Stone Cladding & Niche',
    category: 'Interior',
    location: 'Udumalpet',
    year: '2024',
    image: '/images/projects/interior-golden-slate-cladding.webp',
    description: 'Stacked golden slate stone accent wall with precision spotlighting and luxury flooring',
  },
  {
    id: 4,
    title: 'Bespoke Tiled Veranda Villa',
    category: 'Residential',
    location: 'Udumalpet',
    year: '2024',
    image: '/images/projects/bungalow-tiled-veranda.webp',
    description: 'Spacious residence featuring traditional tiled porch overhang, textured boundary wall, and secure courtyard',
  },
  {
    id: 5,
    title: 'Contemporary Duplex Villa',
    category: 'Residential',
    location: 'Udumalpet',
    year: '2024',
    image: '/images/projects/luxury-duplex-elevation.webp',
    description: 'Multi-level home with glass balcony railings, geometric exterior grooves, and accent lighting',
  },
  {
    id: 6,
    title: 'Handcrafted Teakwood Main Door',
    category: 'Interior',
    location: 'Udumalpet',
    year: '2023',
    image: '/images/projects/interior-carved-teak-door.webp',
    description: 'Artisan hand-carved solid teak wood entrance door with brass fixtures and safety grill',
  },
  {
    id: 7,
    title: 'Coconut Grove Country House',
    category: 'Renovation',
    location: 'Pollachi Road, Udumalpet',
    year: '2023',
    image: '/images/projects/traditional-coconut-grove-villa.webp',
    description: 'Traditional pitched clay-tile roof country farmhouse nestled in a coconut grove setting',
  },
  {
    id: 8,
    title: 'Modern Architectural Villa with Slate Facade',
    category: 'Residential',
    location: 'Udumalpet',
    year: '2024',
    image: '/images/projects/residential-modern-facade.webp',
    description: 'Modern architectural villa featuring custom wooden louvers, designer gate, and premium finish',
  },
];

export const WHY_CHOOSE_US = [
  {
    id: 1,
    title: 'Affordable Pricing',
    description: 'We offer competitive pricing without compromising on quality. Transparent quotes with no hidden charges.',
    icon: 'IndianRupee',
  },
  {
    id: 2,
    title: 'Quality Materials',
    description: 'Only the finest construction materials from trusted suppliers ensuring durability and longevity.',
    icon: 'ShieldCheck',
  },
  {
    id: 3,
    title: 'Experienced Team',
    description: 'Skilled engineers, architects, and craftsmen with 10+ years of collective construction expertise.',
    icon: 'Users',
  },
  {
    id: 4,
    title: 'On-time Delivery',
    description: 'We respect your time. Every project is tracked daily to ensure timely completion as promised.',
    icon: 'Clock',
  },
  {
    id: 5,
    title: 'Professional Communication',
    description: 'Regular project updates, transparent reporting, and responsive customer support throughout.',
    icon: 'MessageSquare',
  },
  {
    id: 6,
    title: 'Customer Satisfaction',
    description: '4.9 Google rating with 41+ happy clients is our most trusted badge of quality work.',
    icon: 'ThumbsUp',
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    location: 'Udumalpet',
    rating: 5,
    text: 'Excellent work by GRN Construction! They built our dream home within the agreed budget and timeline. The quality of materials used is top-notch. Highly recommended for anyone looking for reliable builders in Udumalpet.',
    date: '2 months ago',
    initial: 'R',
  },
  {
    id: 2,
    name: 'Priya Lakshmi',
    location: 'Tiruppur',
    rating: 5,
    text: 'Very professional team. The interior design work they did for our office was outstanding. Proper communication throughout the project. They listened to all our requirements and delivered exactly what we wanted.',
    date: '3 months ago',
    initial: 'P',
  },
  {
    id: 3,
    name: 'Murugan S.',
    location: 'Pollachi',
    rating: 5,
    text: 'GRN Construction renovated our old house beautifully. The cost was very affordable compared to other contractors. They were responsive and completed the work on time. Truly a trusted local construction company.',
    date: '4 months ago',
    initial: 'M',
  },
  {
    id: 4,
    name: 'Kavitha R.',
    location: 'Udumalpet',
    rating: 5,
    text: 'I am very happy with the waterproofing and tile work done by GRN. No leakages since 6 months. The team was clean, professional and courteous. Will definitely hire them again for future construction needs.',
    date: '5 months ago',
    initial: 'K',
  },
  {
    id: 5,
    name: 'Suresh Babu',
    location: 'Coimbatore',
    rating: 5,
    text: 'Built our commercial space with great precision and quality. GRN Construction team is knowledgeable and dedicated. The project manager kept us updated at every stage. Extremely satisfied with the outcome!',
    date: '1 month ago',
    initial: 'S',
  },
];

export const STATS = [
  { label: 'Happy Clients', value: 41, suffix: '+', icon: 'Users' },
  { label: 'Google Rating', value: 4.9, suffix: '/5', icon: 'Star', isDecimal: true },
  { label: 'Years Experience', value: 10, suffix: '+', icon: 'Award' },
  { label: 'Projects Completed', value: 100, suffix: '+', icon: 'Building2' },
];
